"""Initial schema from scratch

Revision ID: 0b5bdb10bee4
Revises: 
Create Date: 2025-02-04 17:10:58.507798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5bdb10bee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('duration_type', sa.String(length=20), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('weather_morning', sa.String(length=50), nullable=True),
    sa.Column('weather_noon', sa.String(length=50), nullable=True),
    sa.Column('day_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_diary_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_diary_id', sa.Integer(), nullable=False),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_diary_id'], ['site_diaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_diary_staff',
    sa.Column('site_diary_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_diary_id'], ['site_diaries.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('site_diary_id', 'staff_id')
    )
    op.create_table('site_diary_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_diary_id', sa.Integer(), nullable=False),
    sa.Column('worker_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_diary_id'], ['site_diaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_diary_workers')
    op.drop_table('site_diary_staff')
    op.drop_table('site_diary_machines')
    op.drop_table('site_diaries')
    op.drop_table('staff')
    op.drop_table('projects')
    # ### end Alembic commands ###
